using System.Text.Json.Serialization;

namespace BouwdepotInvoiceValidator.Infrastructure.Ollama.Models
{
    /// <summary>
    /// Represents the response body from the Ollama /api/chat endpoint (non-streaming).
    /// </summary>
    internal class OllamaChatResponse
    {
        /// <summary>
        /// The model name used for the response.
        /// </summary>
        [JsonPropertyName("model")]
        public string Model { get; set; } = string.Empty;

        /// <summary>
        /// Timestamp of when the response was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// The message generated by the model.
        /// </summary>
        [JsonPropertyName("message")]
        public OllamaChatMessage? Message { get; set; }

        /// <summary>
        /// Indicates if the response generation is complete.
        /// </summary>
        [JsonPropertyName("done")]
        public bool Done { get; set; }

        // --- Optional fields providing usage statistics ---

        /// <summary>
        /// Time spent processing the prompt.
        /// </summary>
        [JsonPropertyName("prompt_eval_duration")]
        public long? PromptEvalDuration { get; set; }

        /// <summary>
        /// Number of tokens in the prompt.
        /// </summary>
        [JsonPropertyName("prompt_eval_count")]
        public int? PromptEvalCount { get; set; }

        /// <summary>
        /// Time spent generating the response.
        /// </summary>
        [JsonPropertyName("eval_duration")]
        public long? EvalDuration { get; set; }

        /// <summary>
        /// Number of tokens in the response.
        /// </summary>
        [JsonPropertyName("eval_count")]
        public int? EvalCount { get; set; }

        /// <summary>
        /// Total duration for the request.
        /// </summary>
        [JsonPropertyName("total_duration")]
        public long? TotalDuration { get; set; }

        /// <summary>
        /// Number of context tokens used (if applicable).
        /// </summary>
        [JsonPropertyName("load_duration")]
        public long? LoadDuration { get; set; }

        // --- Error field ---
        /// <summary>
        /// Error message if the request failed.
        /// </summary>
        [JsonPropertyName("error")]
        public string? Error { get; set; }
    }
}
